stages:
  gen_prep:
    cmd: python src/gen_prep.py
    deps:
      - src/gen_prep.py
      - data/seed/
    outs:
      - data/gen/knowledge_base.jsonl
      - data/gen/prompts_template.txt

  gen_embeddings:
    cmd: python src/create_embeddings.py
    deps:
      - src/create_embeddings.py
      - data/gen/knowledge_base.jsonl
      - params.yaml
    outs:
      - data/gen/embeddings.npy
      - data/gen/ids.npy

  gen_index:
    cmd: python src/build_faiss_index.py
    deps:
      - src/build_faiss_index.py
      - data/gen/embeddings.npy
    outs:
      - data/gen/faiss_index.faiss

  gen_eval:
    cmd: python src/gen_evaluate.py --output metrics/gen_eval_report.json
    deps:
      - src/gen_evaluate.py
      - data/validation/
      - params.yaml
    outs:
      - metrics/gen_eval_report.json
