genai:
  backend: "local"            # options: local | openai
  hf_model: "gpt2"            # small default; replace with your model e.g. "gpt2-medium" or an instruct model
  openai_model: "gpt-4o-mini" # if using OpenAI
  embeddings:
    backend: "hf"             # hf or openai
    hf_model: "sentence-transformers/all-MiniLM-L6-v2"
    openai_model: "text-embedding-3-small"
  retrieval:
    top_k: 4
  generation:
    max_new_tokens: 128
    temperature: 0.0
ct:
  finetune_enabled: false
  finetune_epochs: 1
  finetune_batch: 8
